using System.Collections.Generic;
using UnityEngine;

#if (UNITY_EDITOR)
using UnityEditor;
#endif

namespace Cosmetics
{
    #if (UNITY_EDITOR)
    [InitializeOnLoad]
    [CreateAssetMenu(fileName = "Cosmetic Database", menuName = "ManaCycle/Cosmetic Database")]
    #endif
    public class CosmeticDatabase : ScriptableObject
    {
        public List<IconPackScriptable> iconPacks;
        public List<PaletteColorScriptable> colors;

        // every icon and color contained within the icon and color packs, generated by RefreshData
        [System.NonSerialized] public List<ManaIcon> icons;
        // [System.NonSerialized] public List<ManaPalette> colors;

        void RefreshData()
        {
            icons = new List<ManaIcon>();
            // colors = new List<ManaPalette>();
            // assuming each icon in every pack is unique to one another
            foreach(IconPackScriptable scriptable in iconPacks)
            {
                icons.AddRange(scriptable.iconPack.icons);
            }
        }

        void OnEnable()
        {
            // Debug.Log("Cosmetic database awake");
            RefreshData();
        }
    }
}